// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR5sR5de_BjiRHSsqMgWcdzoYndUlH54Q',
    appId: '1:797532736455:web:7c8beba70482cfef48a7e2',
    messagingSenderId: '797532736455',
    projectId: 'carraze-a0acd',
    authDomain: 'carraze-a0acd.firebaseapp.com',
    storageBucket: 'carraze-a0acd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmnYKK_wAiWX74T2L-69YG3xvki8AisNU',
    appId: '1:797532736455:android:ff56800cf9c39e1d48a7e2',
    messagingSenderId: '797532736455',
    projectId: 'carraze-a0acd',
    storageBucket: 'carraze-a0acd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMo6CyQpPOahRvl-R--c_LFYOsvp7vQTI',
    appId: '1:797532736455:ios:c8231faa44afc43c48a7e2',
    messagingSenderId: '797532736455',
    projectId: 'carraze-a0acd',
    storageBucket: 'carraze-a0acd.firebasestorage.app',
    iosBundleId: 'com.example.carraze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMo6CyQpPOahRvl-R--c_LFYOsvp7vQTI',
    appId: '1:797532736455:ios:c8231faa44afc43c48a7e2',
    messagingSenderId: '797532736455',
    projectId: 'carraze-a0acd',
    storageBucket: 'carraze-a0acd.firebasestorage.app',
    iosBundleId: 'com.example.carraze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR5sR5de_BjiRHSsqMgWcdzoYndUlH54Q',
    appId: '1:797532736455:web:505dc70b68c0551d48a7e2',
    messagingSenderId: '797532736455',
    projectId: 'carraze-a0acd',
    authDomain: 'carraze-a0acd.firebaseapp.com',
    storageBucket: 'carraze-a0acd.firebasestorage.app',
  );
}
